# Generated by Django 5.2.7 on 2025-10-23 06:29

import application.user.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_cliente'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usuario',
            managers=[
                ('objects', application.user.models.UsuarioManager()),
            ],
        ),
    ]
