# Generated by Django 5.2.7 on 2026-02-20 21:06

import application.user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_usuario_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supervisor',
            fields=[
            ],
            options={
                'verbose_name': 'Supervisor',
                'verbose_name_plural': 'Supervisores',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('user.usuario',),
            managers=[
                ('objects', application.user.models.UsuarioManager()),
            ],
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.CharField(choices=[('cliente', 'Cliente'), ('admin', 'Administrador'), ('supervisor', 'Supervisor')], default='cliente', max_length=20),
        ),
    ]
