# Generated by Django 5.2.7 on 2025-11-07 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_cart_order_orderitem_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
