# Generated by Django 5.2.7 on 2025-11-19 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_remove_orderitem_order_remove_orderitem_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='capacidad',
            field=models.CharField(blank=True, help_text='Capacidad del producto (250L, 15kg, 1.5L, etc.)', max_length=50, null=True, verbose_name='Capacidad'),
        ),
        migrations.AddField(
            model_name='producto',
            name='caracteristicas_destacadas',
            field=models.TextField(blank=True, help_text='Separadas por comas (ej: No Frost, Inverter, Digital, Automático)', null=True, verbose_name='Características destacadas'),
        ),
        migrations.AddField(
            model_name='producto',
            name='color',
            field=models.CharField(blank=True, help_text='Color principal del producto', max_length=50, null=True, verbose_name='Color'),
        ),
        migrations.AddField(
            model_name='producto',
            name='garantia_meses',
            field=models.PositiveIntegerField(blank=True, help_text='Meses de garantía del producto', null=True, verbose_name='Garantía (meses)'),
        ),
        migrations.AddField(
            model_name='producto',
            name='marca',
            field=models.CharField(blank=True, help_text='Marca del electrodoméstico (Samsung, LG, Haceb, etc.)', max_length=100, null=True, verbose_name='Marca'),
        ),
        migrations.AddField(
            model_name='producto',
            name='potencia',
            field=models.CharField(blank=True, help_text='Potencia eléctrica (1200W, 800W, etc.)', max_length=50, null=True, verbose_name='Potencia'),
        ),
    ]
