# Generated by Django 5.2.7 on 2026-03-07 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_resena'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerPromocion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120)),
                ('subtitulo', models.CharField(blank=True, max_length=200)),
                ('imagen', models.ImageField(upload_to='banners/')),
                ('url_destino', models.CharField(default='/productos/', max_length=200)),
                ('texto_boton', models.CharField(default='Ver ofertas', max_length=50)),
                ('color_boton', models.CharField(default='#f59e0b', max_length=20)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Banner Promocional',
                'verbose_name_plural': 'Banners Promocionales',
                'ordering': ['orden'],
            },
        ),
    ]
