# Generated by Django 5.2.7 on 2026-03-16 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_bannerpromocion'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Selecciona la categoría padre si esta es una subcategoría', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategorias', to='product.categoria', verbose_name='Categoría padre'),
        ),
    ]
