# Generated by Django 5.2.7 on 2026-03-27 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_categoria_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeccionPromocional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('subtitulo', models.CharField(blank=True, max_length=200)),
                ('icono', models.CharField(choices=[('🔥', '🔥 Fuego'), ('⚡', '⚡ Rayo'), ('🏆', '🏆 Trofeo'), ('⭐', '⭐ Estrella'), ('✨', '✨ Brillos'), ('🎯', '🎯 Diana'), ('💥', '💥 Explosión'), ('🛒', '🛒 Carrito'), ('🖤', '🖤 Negro'), ('🎉', '🎉 Fiesta')], default='🔥', max_length=10)),
                ('color_acento', models.CharField(choices=[('red', 'Rojo'), ('blue', 'Azul'), ('yellow', 'Amarillo'), ('green', 'Verde'), ('purple', 'Morado'), ('black', 'Negro'), ('orange', 'Naranja')], default='red', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('mostrar_timer', models.BooleanField(default=False)),
                ('url_ver_todo', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Sección Promocional',
                'verbose_name_plural': 'Secciones Promocionales',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='ProductoSeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descuento_porcentaje', models.DecimalField(decimal_places=2, max_digits=5)),
                ('precio_promocional', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('destacado', models.BooleanField(default=False)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secciones', to='product.producto')),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_seccion', to='product.seccionpromocional')),
            ],
            options={
                'verbose_name': 'Producto en Sección',
                'verbose_name_plural': 'Productos en Secciones',
                'ordering': ['orden'],
                'unique_together': {('seccion', 'producto')},
            },
        ),
    ]
