# Generated by Django 5.2.7 on 2026-02-24 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_promocion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenproducto',
            name='imagen',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen_principal',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
