# Generated by Django 5.2.7 on 2025-11-09 03:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_remove_pedido_usuario_order_orderitem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(help_text='Ingrese 10 dígitos numéricos', max_length=10, validators=[django.core.validators.RegexValidator(message='El número de teléfono debe contener exactamente 10 dígitos numéricos.', regex='^\\d{10}$')], verbose_name='Teléfono'),
        ),
    ]
