# Generated by Django 5.2.7 on 2025-11-21 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_order_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobado'), ('declined', 'Rechazado'), ('error', 'Error')], default='pending', max_length=20, verbose_name='Estado del pago'),
        ),
        migrations.AddField(
            model_name='order',
            name='wompi_payment_link',
            field=models.URLField(blank=True, null=True, verbose_name='Link de pago Wompi'),
        ),
        migrations.AddField(
            model_name='order',
            name='wompi_reference',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Referencia de pago Wompi'),
        ),
        migrations.AddField(
            model_name='order',
            name='wompi_transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID de transacción Wompi'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('credit_card', 'Tarjeta de Crédito'), ('debit_card', 'Tarjeta de Débito'), ('pse', 'PSE'), ('nequi', 'Nequi'), ('bancolombia', 'Bancolombia Transfer'), ('cash', 'Efectivo Contraentrega')], default='credit_card', max_length=20),
        ),
    ]
